logging:
  level:
    root: info
    it.labtech.base.api: debug

spring:
  application:
    name: labtech-base

server:
  port: ${APPLICATION_HOST_PORT:8080}

management:
  endpoint:
    health:
      probes:
        enabled: true
    web:
      exposure:
        include: "info,health,metrics,mappings"