logging:
  level:
    root: info
    it.labtech.base.api: debug

spring:
  application:
    name: base
    cloud:
      loadbalancer:
        ribbon:
          enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://dev00.labtech.it/auth/realms/labtech

server:
  port: ${APPLICATION_HOST_PORT:8080}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health,metrics,mappings,caches"

labtech:
  api:
    rest:
      base-path: /api/rest

---
spring:
  config:
    import: optional:configserver:${CONFIGSERVER_URL}
    activate:
      on-profile: eureka
  autoconfigure:
    exclude:
      # Exclusion for kubernetes
      - org.springframework.cloud.kubernetes.discovery.KubernetesDiscoveryClientAutoConfiguration
      - org.springframework.cloud.kubernetes.discovery.KubernetesCatalogWatchAutoConfiguration

---
spring:
  config:
    activate:
      on-profile: kubernetes
  autoconfigure:
    exclude:
      # Exclusion for Eureka client
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
      - org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration