logging:
  level:
    root: info
    it.labtech.base.api: debug

spring:
  application:
    name: labtech-base
server:
  port: 8081
management:
  endpoint:
    health:
      probes:
        enabled: true
    web:
      exposure:
        include: "info,health,metrics,mappings"