spring:
  config:
    activate:
      on-profile: kubernetes
  autoconfigure:
    exclude:
      # Exclusion for Eureka client
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
      - org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration